name = "Merly"
uuid = "5b70daea-9db9-5a46-aedf-2142e553ecc5"
repo = "https://github.com/neomatrixcode/Merly.jl"
authors = ["Josue Acevedo Maldonado <josuecevedo@gmail.com>"]
version = "1.0.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"

[compat]
julia = "1.5"
